In [3]:
import numpy as np

In [19]:
A = np.matrix([[0.44, 0.12], 
               [0.56, 0.88]])

w, v = np.linalg.eig(A)

In [20]:
w; v

matrix([[-0.70710678, -0.20952909],
        [ 0.70710678, -0.97780241]])

In [21]:
w

array([0.32, 1.  ])

In [22]:
v

matrix([[-0.70710678, -0.20952909],
        [ 0.70710678, -0.97780241]])

In [23]:
v_inv = np.linalg.inv(v)
v_inv

matrix([[-1.16464646,  0.2495671 ],
        [-0.84222477, -0.84222477]])